spring:
  application:
    name: oauth2-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oauth2 # ??? ??? ??
          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs # OAuth 2.0 JwkSetUri ?? ???
          #jws-algorithms: RS256 # OAuth 2.0 JWS ?? ????
          #audiences: http://localhost:8082 # ??? ??
          #public-key-location: classpath:certs/publicKey.txt # OAuth 2.0 JWS ??? ?? PublicKey ?? ??
server:
  port: 8082
