spring:
  application:
    name: oauth2-resource-server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token/introspect
          client-id: oauth2-client-app
          client-secret: secret
        #jwt:
          #issuer-uri: http://localhost:8080/realms/oauth2
          #jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
          #audiences: http://localhost:8082
          #jws-algorithms: RS256
          #public-key-location: classpath:certs/publicKey.txt
server:
  port: 8082
